<?php

function sunflower_menu() {
  return ['sunflower' => [
    'menu_name'       => 'main-menu',
    'type'            => MENU_NORMAL_ITEM,
    'title'           => t('Sunflower'),
    'description'     => t('An abstract simulation of a sunflower’s growth pattern using the HTML canvas element and a little math.'),
    'page callback'   => 'sunflower_view',
    'file'            => 'sunflower.view.inc',
    'access callback' => TRUE,
    'weight'          => 1,
    ]
  ];
}
