<?php

function sunflower_menu() {
    return array( 'sunflower' => array(
        'menu_name' => 'main-menu',
        'type' => MENU_NORMAL_ITEM,
        'title' => 'Sunflower',
        'description' => t('An abstract simulation of a sunflower’s growth pattern using the HTML canvas element and a little math.'),
        'page callback' => 'sunflower_view',
        'access callback' => TRUE,
        'weight' => 1,
    ));
}



function sunflower_view() {
    drupal_add_css(drupal_get_path('module', 'sunflower') .'/sunflower.css');
    drupal_add_js(drupal_get_path('module', 'sunflower') .'/sunflower.js');
    $html = <<<'END_OF_TEXT'
<article id="sunflower">
<canvas id="canvas" width="580" height="580"></canvas>
<div id="controls">
<input id="controlStep" type="range" min="0" max="0" step="0" value="0">
<div id="buttons">
<img id="controlBegin" src="/sites/default/modules/sunflower/media-skip-backward.svg"  width="48" height="48" alt="beginning" title="start at beginning">
<img id="controlStart" src="/sites/default/modules/sunflower/media-playback-start.svg" width="48" height="48" alt="start"     title="begin animation">
<img id="controlPause" src="/sites/default/modules/sunflower/media-playback-pause.svg" width="48" height="48" alt="pause"     title="pause">
<img id="controlEnd"   src="/sites/default/modules/sunflower/media-skip-forward.svg"   width="48" height="48" alt="end"       title="jump to end">
</div>
</div>
</article>
END_OF_TEXT;
    return $html;
}
